#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangGiay
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlcuahanggiay")]
	public partial class QLCuaHangBanGiayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertchiTietHoaDon(chiTietHoaDon instance);
    partial void UpdatechiTietHoaDon(chiTietHoaDon instance);
    partial void DeletechiTietHoaDon(chiTietHoaDon instance);
    partial void InsertchiTietPhieuNhap(chiTietPhieuNhap instance);
    partial void UpdatechiTietPhieuNhap(chiTietPhieuNhap instance);
    partial void DeletechiTietPhieuNhap(chiTietPhieuNhap instance);
    partial void InsertGiay(Giay instance);
    partial void UpdateGiay(Giay instance);
    partial void DeleteGiay(Giay instance);
    partial void InserthoaDonBanHang(hoaDonBanHang instance);
    partial void UpdatehoaDonBanHang(hoaDonBanHang instance);
    partial void DeletehoaDonBanHang(hoaDonBanHang instance);
    partial void InsertkhachHang(khachHang instance);
    partial void UpdatekhachHang(khachHang instance);
    partial void DeletekhachHang(khachHang instance);
    partial void Insertnhacungcap(nhacungcap instance);
    partial void Updatenhacungcap(nhacungcap instance);
    partial void Deletenhacungcap(nhacungcap instance);
    partial void InsertnhanVien(nhanVien instance);
    partial void UpdatenhanVien(nhanVien instance);
    partial void DeletenhanVien(nhanVien instance);
    partial void Insertphieunhap(phieunhap instance);
    partial void Updatephieunhap(phieunhap instance);
    partial void Deletephieunhap(phieunhap instance);
    partial void InserttaiKhoan(taiKhoan instance);
    partial void UpdatetaiKhoan(taiKhoan instance);
    partial void DeletetaiKhoan(taiKhoan instance);
    #endregion
		
		public QLCuaHangBanGiayDataContext() : 
				base(global::CuaHangGiay.Properties.Settings.Default.qlcuahanggiayConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangBanGiayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangBanGiayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangBanGiayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangBanGiayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chiTietHoaDon> chiTietHoaDons
		{
			get
			{
				return this.GetTable<chiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<chiTietPhieuNhap> chiTietPhieuNhaps
		{
			get
			{
				return this.GetTable<chiTietPhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<Giay> Giays
		{
			get
			{
				return this.GetTable<Giay>();
			}
		}
		
		public System.Data.Linq.Table<hoaDonBanHang> hoaDonBanHangs
		{
			get
			{
				return this.GetTable<hoaDonBanHang>();
			}
		}
		
		public System.Data.Linq.Table<khachHang> khachHangs
		{
			get
			{
				return this.GetTable<khachHang>();
			}
		}
		
		public System.Data.Linq.Table<nhacungcap> nhacungcaps
		{
			get
			{
				return this.GetTable<nhacungcap>();
			}
		}
		
		public System.Data.Linq.Table<nhanVien> nhanViens
		{
			get
			{
				return this.GetTable<nhanVien>();
			}
		}
		
		public System.Data.Linq.Table<phieunhap> phieunhaps
		{
			get
			{
				return this.GetTable<phieunhap>();
			}
		}
		
		public System.Data.Linq.Table<taiKhoan> taiKhoans
		{
			get
			{
				return this.GetTable<taiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiTietHoaDon")]
	public partial class chiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mahdbh;
		
		private int _magiay;
		
		private System.Nullable<int> _soluong;
		
		private EntityRef<Giay> _Giay;
		
		private EntityRef<hoaDonBanHang> _hoaDonBanHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahdbhChanging(int value);
    partial void OnmahdbhChanged();
    partial void OnmagiayChanging(int value);
    partial void OnmagiayChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    #endregion
		
		public chiTietHoaDon()
		{
			this._Giay = default(EntityRef<Giay>);
			this._hoaDonBanHang = default(EntityRef<hoaDonBanHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahdbh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mahdbh
		{
			get
			{
				return this._mahdbh;
			}
			set
			{
				if ((this._mahdbh != value))
				{
					if (this._hoaDonBanHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmahdbhChanging(value);
					this.SendPropertyChanging();
					this._mahdbh = value;
					this.SendPropertyChanged("mahdbh");
					this.OnmahdbhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magiay", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int magiay
		{
			get
			{
				return this._magiay;
			}
			set
			{
				if ((this._magiay != value))
				{
					if (this._Giay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmagiayChanging(value);
					this.SendPropertyChanging();
					this._magiay = value;
					this.SendPropertyChanged("magiay");
					this.OnmagiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Giay_chiTietHoaDon", Storage="_Giay", ThisKey="magiay", OtherKey="magiay", IsForeignKey=true)]
		public Giay Giay
		{
			get
			{
				return this._Giay.Entity;
			}
			set
			{
				Giay previousValue = this._Giay.Entity;
				if (((previousValue != value) 
							|| (this._Giay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Giay.Entity = null;
						previousValue.chiTietHoaDons.Remove(this);
					}
					this._Giay.Entity = value;
					if ((value != null))
					{
						value.chiTietHoaDons.Add(this);
						this._magiay = value.magiay;
					}
					else
					{
						this._magiay = default(int);
					}
					this.SendPropertyChanged("Giay");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoaDonBanHang_chiTietHoaDon", Storage="_hoaDonBanHang", ThisKey="mahdbh", OtherKey="mahdbh", IsForeignKey=true)]
		public hoaDonBanHang hoaDonBanHang
		{
			get
			{
				return this._hoaDonBanHang.Entity;
			}
			set
			{
				hoaDonBanHang previousValue = this._hoaDonBanHang.Entity;
				if (((previousValue != value) 
							|| (this._hoaDonBanHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoaDonBanHang.Entity = null;
						previousValue.chiTietHoaDons.Remove(this);
					}
					this._hoaDonBanHang.Entity = value;
					if ((value != null))
					{
						value.chiTietHoaDons.Add(this);
						this._mahdbh = value.mahdbh;
					}
					else
					{
						this._mahdbh = default(int);
					}
					this.SendPropertyChanged("hoaDonBanHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiTietPhieuNhap")]
	public partial class chiTietPhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maphieunhap;
		
		private int _magiay;
		
		private System.Nullable<int> _soluong;
		
		private EntityRef<Giay> _Giay;
		
		private EntityRef<phieunhap> _phieunhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphieunhapChanging(int value);
    partial void OnmaphieunhapChanged();
    partial void OnmagiayChanging(int value);
    partial void OnmagiayChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    #endregion
		
		public chiTietPhieuNhap()
		{
			this._Giay = default(EntityRef<Giay>);
			this._phieunhap = default(EntityRef<phieunhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieunhap", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maphieunhap
		{
			get
			{
				return this._maphieunhap;
			}
			set
			{
				if ((this._maphieunhap != value))
				{
					if (this._phieunhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphieunhapChanging(value);
					this.SendPropertyChanging();
					this._maphieunhap = value;
					this.SendPropertyChanged("maphieunhap");
					this.OnmaphieunhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magiay", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int magiay
		{
			get
			{
				return this._magiay;
			}
			set
			{
				if ((this._magiay != value))
				{
					if (this._Giay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmagiayChanging(value);
					this.SendPropertyChanging();
					this._magiay = value;
					this.SendPropertyChanged("magiay");
					this.OnmagiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Giay_chiTietPhieuNhap", Storage="_Giay", ThisKey="magiay", OtherKey="magiay", IsForeignKey=true)]
		public Giay Giay
		{
			get
			{
				return this._Giay.Entity;
			}
			set
			{
				Giay previousValue = this._Giay.Entity;
				if (((previousValue != value) 
							|| (this._Giay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Giay.Entity = null;
						previousValue.chiTietPhieuNhaps.Remove(this);
					}
					this._Giay.Entity = value;
					if ((value != null))
					{
						value.chiTietPhieuNhaps.Add(this);
						this._magiay = value.magiay;
					}
					else
					{
						this._magiay = default(int);
					}
					this.SendPropertyChanged("Giay");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieunhap_chiTietPhieuNhap", Storage="_phieunhap", ThisKey="maphieunhap", OtherKey="maphieunhap", IsForeignKey=true)]
		public phieunhap phieunhap
		{
			get
			{
				return this._phieunhap.Entity;
			}
			set
			{
				phieunhap previousValue = this._phieunhap.Entity;
				if (((previousValue != value) 
							|| (this._phieunhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phieunhap.Entity = null;
						previousValue.chiTietPhieuNhaps.Remove(this);
					}
					this._phieunhap.Entity = value;
					if ((value != null))
					{
						value.chiTietPhieuNhaps.Add(this);
						this._maphieunhap = value.maphieunhap;
					}
					else
					{
						this._maphieunhap = default(int);
					}
					this.SendPropertyChanged("phieunhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Giay")]
	public partial class Giay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _magiay;
		
		private string _tengiay;
		
		private string _thuonghieu;
		
		private string _loai;
		
		private System.Nullable<double> _giaban;
		
		private System.Nullable<double> _gianhap;
		
		private System.Nullable<int> _soluongcon;
		
		private EntitySet<chiTietHoaDon> _chiTietHoaDons;
		
		private EntitySet<chiTietPhieuNhap> _chiTietPhieuNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmagiayChanging(int value);
    partial void OnmagiayChanged();
    partial void OntengiayChanging(string value);
    partial void OntengiayChanged();
    partial void OnthuonghieuChanging(string value);
    partial void OnthuonghieuChanged();
    partial void OnloaiChanging(string value);
    partial void OnloaiChanged();
    partial void OngiabanChanging(System.Nullable<double> value);
    partial void OngiabanChanged();
    partial void OngianhapChanging(System.Nullable<double> value);
    partial void OngianhapChanged();
    partial void OnsoluongconChanging(System.Nullable<int> value);
    partial void OnsoluongconChanged();
    #endregion
		
		public Giay()
		{
			this._chiTietHoaDons = new EntitySet<chiTietHoaDon>(new Action<chiTietHoaDon>(this.attach_chiTietHoaDons), new Action<chiTietHoaDon>(this.detach_chiTietHoaDons));
			this._chiTietPhieuNhaps = new EntitySet<chiTietPhieuNhap>(new Action<chiTietPhieuNhap>(this.attach_chiTietPhieuNhaps), new Action<chiTietPhieuNhap>(this.detach_chiTietPhieuNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magiay", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int magiay
		{
			get
			{
				return this._magiay;
			}
			set
			{
				if ((this._magiay != value))
				{
					this.OnmagiayChanging(value);
					this.SendPropertyChanging();
					this._magiay = value;
					this.SendPropertyChanged("magiay");
					this.OnmagiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tengiay", DbType="NVarChar(20)")]
		public string tengiay
		{
			get
			{
				return this._tengiay;
			}
			set
			{
				if ((this._tengiay != value))
				{
					this.OntengiayChanging(value);
					this.SendPropertyChanging();
					this._tengiay = value;
					this.SendPropertyChanged("tengiay");
					this.OntengiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuonghieu", DbType="NVarChar(30)")]
		public string thuonghieu
		{
			get
			{
				return this._thuonghieu;
			}
			set
			{
				if ((this._thuonghieu != value))
				{
					this.OnthuonghieuChanging(value);
					this.SendPropertyChanging();
					this._thuonghieu = value;
					this.SendPropertyChanged("thuonghieu");
					this.OnthuonghieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string loai
		{
			get
			{
				return this._loai;
			}
			set
			{
				if ((this._loai != value))
				{
					this.OnloaiChanging(value);
					this.SendPropertyChanging();
					this._loai = value;
					this.SendPropertyChanged("loai");
					this.OnloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaban", DbType="Float")]
		public System.Nullable<double> giaban
		{
			get
			{
				return this._giaban;
			}
			set
			{
				if ((this._giaban != value))
				{
					this.OngiabanChanging(value);
					this.SendPropertyChanging();
					this._giaban = value;
					this.SendPropertyChanged("giaban");
					this.OngiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gianhap", DbType="Float")]
		public System.Nullable<double> gianhap
		{
			get
			{
				return this._gianhap;
			}
			set
			{
				if ((this._gianhap != value))
				{
					this.OngianhapChanging(value);
					this.SendPropertyChanging();
					this._gianhap = value;
					this.SendPropertyChanged("gianhap");
					this.OngianhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongcon", DbType="Int")]
		public System.Nullable<int> soluongcon
		{
			get
			{
				return this._soluongcon;
			}
			set
			{
				if ((this._soluongcon != value))
				{
					this.OnsoluongconChanging(value);
					this.SendPropertyChanging();
					this._soluongcon = value;
					this.SendPropertyChanged("soluongcon");
					this.OnsoluongconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Giay_chiTietHoaDon", Storage="_chiTietHoaDons", ThisKey="magiay", OtherKey="magiay")]
		public EntitySet<chiTietHoaDon> chiTietHoaDons
		{
			get
			{
				return this._chiTietHoaDons;
			}
			set
			{
				this._chiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Giay_chiTietPhieuNhap", Storage="_chiTietPhieuNhaps", ThisKey="magiay", OtherKey="magiay")]
		public EntitySet<chiTietPhieuNhap> chiTietPhieuNhaps
		{
			get
			{
				return this._chiTietPhieuNhaps;
			}
			set
			{
				this._chiTietPhieuNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietHoaDons(chiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Giay = this;
		}
		
		private void detach_chiTietHoaDons(chiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Giay = null;
		}
		
		private void attach_chiTietPhieuNhaps(chiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.Giay = this;
		}
		
		private void detach_chiTietPhieuNhaps(chiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.Giay = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoaDonBanHang")]
	public partial class hoaDonBanHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mahdbh;
		
		private System.Nullable<int> _manv;
		
		private System.Nullable<int> _makh;
		
		private string _ngayban;
		
		private System.Nullable<double> _tongtien;
		
		private System.Nullable<int> _giamgia;
		
		private EntitySet<chiTietHoaDon> _chiTietHoaDons;
		
		private EntityRef<khachHang> _khachHang;
		
		private EntityRef<nhanVien> _nhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahdbhChanging(int value);
    partial void OnmahdbhChanged();
    partial void OnmanvChanging(System.Nullable<int> value);
    partial void OnmanvChanged();
    partial void OnmakhChanging(System.Nullable<int> value);
    partial void OnmakhChanged();
    partial void OnngaybanChanging(string value);
    partial void OnngaybanChanged();
    partial void OntongtienChanging(System.Nullable<double> value);
    partial void OntongtienChanged();
    partial void OngiamgiaChanging(System.Nullable<int> value);
    partial void OngiamgiaChanged();
    #endregion
		
		public hoaDonBanHang()
		{
			this._chiTietHoaDons = new EntitySet<chiTietHoaDon>(new Action<chiTietHoaDon>(this.attach_chiTietHoaDons), new Action<chiTietHoaDon>(this.detach_chiTietHoaDons));
			this._khachHang = default(EntityRef<khachHang>);
			this._nhanVien = default(EntityRef<nhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahdbh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mahdbh
		{
			get
			{
				return this._mahdbh;
			}
			set
			{
				if ((this._mahdbh != value))
				{
					this.OnmahdbhChanging(value);
					this.SendPropertyChanging();
					this._mahdbh = value;
					this.SendPropertyChanged("mahdbh");
					this.OnmahdbhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="Int")]
		public System.Nullable<int> manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._nhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="Int")]
		public System.Nullable<int> makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					if (this._khachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayban", DbType="NChar(30)")]
		public string ngayban
		{
			get
			{
				return this._ngayban;
			}
			set
			{
				if ((this._ngayban != value))
				{
					this.OnngaybanChanging(value);
					this.SendPropertyChanging();
					this._ngayban = value;
					this.SendPropertyChanged("ngayban");
					this.OnngaybanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Float")]
		public System.Nullable<double> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamgia", DbType="Int")]
		public System.Nullable<int> giamgia
		{
			get
			{
				return this._giamgia;
			}
			set
			{
				if ((this._giamgia != value))
				{
					this.OngiamgiaChanging(value);
					this.SendPropertyChanging();
					this._giamgia = value;
					this.SendPropertyChanged("giamgia");
					this.OngiamgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoaDonBanHang_chiTietHoaDon", Storage="_chiTietHoaDons", ThisKey="mahdbh", OtherKey="mahdbh")]
		public EntitySet<chiTietHoaDon> chiTietHoaDons
		{
			get
			{
				return this._chiTietHoaDons;
			}
			set
			{
				this._chiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachHang_hoaDonBanHang", Storage="_khachHang", ThisKey="makh", OtherKey="makh", IsForeignKey=true)]
		public khachHang khachHang
		{
			get
			{
				return this._khachHang.Entity;
			}
			set
			{
				khachHang previousValue = this._khachHang.Entity;
				if (((previousValue != value) 
							|| (this._khachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachHang.Entity = null;
						previousValue.hoaDonBanHangs.Remove(this);
					}
					this._khachHang.Entity = value;
					if ((value != null))
					{
						value.hoaDonBanHangs.Add(this);
						this._makh = value.makh;
					}
					else
					{
						this._makh = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_hoaDonBanHang", Storage="_nhanVien", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public nhanVien nhanVien
		{
			get
			{
				return this._nhanVien.Entity;
			}
			set
			{
				nhanVien previousValue = this._nhanVien.Entity;
				if (((previousValue != value) 
							|| (this._nhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanVien.Entity = null;
						previousValue.hoaDonBanHangs.Remove(this);
					}
					this._nhanVien.Entity = value;
					if ((value != null))
					{
						value.hoaDonBanHangs.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(Nullable<int>);
					}
					this.SendPropertyChanged("nhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietHoaDons(chiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.hoaDonBanHang = this;
		}
		
		private void detach_chiTietHoaDons(chiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.hoaDonBanHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachHang")]
	public partial class khachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _makh;
		
		private string _tenkh;
		
		private string _sodt;
		
		private string _diachi;
		
		private EntitySet<hoaDonBanHang> _hoaDonBanHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhChanging(int value);
    partial void OnmakhChanged();
    partial void OntenkhChanging(string value);
    partial void OntenkhChanged();
    partial void OnsodtChanging(string value);
    partial void OnsodtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public khachHang()
		{
			this._hoaDonBanHangs = new EntitySet<hoaDonBanHang>(new Action<hoaDonBanHang>(this.attach_hoaDonBanHangs), new Action<hoaDonBanHang>(this.detach_hoaDonBanHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkh", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string tenkh
		{
			get
			{
				return this._tenkh;
			}
			set
			{
				if ((this._tenkh != value))
				{
					this.OntenkhChanging(value);
					this.SendPropertyChanging();
					this._tenkh = value;
					this.SendPropertyChanged("tenkh");
					this.OntenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodt", DbType="VarChar(11)")]
		public string sodt
		{
			get
			{
				return this._sodt;
			}
			set
			{
				if ((this._sodt != value))
				{
					this.OnsodtChanging(value);
					this.SendPropertyChanging();
					this._sodt = value;
					this.SendPropertyChanged("sodt");
					this.OnsodtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachHang_hoaDonBanHang", Storage="_hoaDonBanHangs", ThisKey="makh", OtherKey="makh")]
		public EntitySet<hoaDonBanHang> hoaDonBanHangs
		{
			get
			{
				return this._hoaDonBanHangs;
			}
			set
			{
				this._hoaDonBanHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoaDonBanHangs(hoaDonBanHang entity)
		{
			this.SendPropertyChanging();
			entity.khachHang = this;
		}
		
		private void detach_hoaDonBanHangs(hoaDonBanHang entity)
		{
			this.SendPropertyChanging();
			entity.khachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhacungcap")]
	public partial class nhacungcap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mancc;
		
		private string _tenncc;
		
		private string _dienthoai;
		
		private string _email;
		
		private string _diachi;
		
		private EntitySet<phieunhap> _phieunhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanccChanging(int value);
    partial void OnmanccChanged();
    partial void OntennccChanging(string value);
    partial void OntennccChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public nhacungcap()
		{
			this._phieunhaps = new EntitySet<phieunhap>(new Action<phieunhap>(this.attach_phieunhaps), new Action<phieunhap>(this.detach_phieunhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mancc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mancc
		{
			get
			{
				return this._mancc;
			}
			set
			{
				if ((this._mancc != value))
				{
					this.OnmanccChanging(value);
					this.SendPropertyChanging();
					this._mancc = value;
					this.SendPropertyChanged("mancc");
					this.OnmanccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenncc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenncc
		{
			get
			{
				return this._tenncc;
			}
			set
			{
				if ((this._tenncc != value))
				{
					this.OntennccChanging(value);
					this.SendPropertyChanging();
					this._tenncc = value;
					this.SendPropertyChanged("tenncc");
					this.OntennccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="VarChar(20)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(20)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhacungcap_phieunhap", Storage="_phieunhaps", ThisKey="mancc", OtherKey="mancc")]
		public EntitySet<phieunhap> phieunhaps
		{
			get
			{
				return this._phieunhaps;
			}
			set
			{
				this._phieunhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhacungcap = this;
		}
		
		private void detach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhacungcap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanVien")]
	public partial class nhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _manv;
		
		private string _tennv;
		
		private string _gioitinh;
		
		private string _ngaysinh;
		
		private string _diachi;
		
		private string _sodienthoai;
		
		private string _email;
		
		private EntitySet<hoaDonBanHang> _hoaDonBanHangs;
		
		private EntitySet<phieunhap> _phieunhaps;
		
		private EntityRef<taiKhoan> _taiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(int value);
    partial void OnmanvChanged();
    partial void OntennvChanging(string value);
    partial void OntennvChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(string value);
    partial void OnngaysinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public nhanVien()
		{
			this._hoaDonBanHangs = new EntitySet<hoaDonBanHang>(new Action<hoaDonBanHang>(this.attach_hoaDonBanHangs), new Action<hoaDonBanHang>(this.detach_hoaDonBanHangs));
			this._phieunhaps = new EntitySet<phieunhap>(new Action<phieunhap>(this.attach_phieunhaps), new Action<phieunhap>(this.detach_phieunhaps));
			this._taiKhoan = default(EntityRef<taiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennv", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string tennv
		{
			get
			{
				return this._tennv;
			}
			set
			{
				if ((this._tennv != value))
				{
					this.OntennvChanging(value);
					this.SendPropertyChanging();
					this._tennv = value;
					this.SendPropertyChanged("tennv");
					this.OntennvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="NChar(12) NOT NULL", CanBeNull=false)]
		public string ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="NChar(11)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_hoaDonBanHang", Storage="_hoaDonBanHangs", ThisKey="manv", OtherKey="manv")]
		public EntitySet<hoaDonBanHang> hoaDonBanHangs
		{
			get
			{
				return this._hoaDonBanHangs;
			}
			set
			{
				this._hoaDonBanHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_phieunhap", Storage="_phieunhaps", ThisKey="manv", OtherKey="manv")]
		public EntitySet<phieunhap> phieunhaps
		{
			get
			{
				return this._phieunhaps;
			}
			set
			{
				this._phieunhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_taiKhoan", Storage="_taiKhoan", ThisKey="manv", OtherKey="manv", IsUnique=true, IsForeignKey=false)]
		public taiKhoan taiKhoan
		{
			get
			{
				return this._taiKhoan.Entity;
			}
			set
			{
				taiKhoan previousValue = this._taiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._taiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._taiKhoan.Entity = null;
						previousValue.nhanVien = null;
					}
					this._taiKhoan.Entity = value;
					if ((value != null))
					{
						value.nhanVien = this;
					}
					this.SendPropertyChanged("taiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoaDonBanHangs(hoaDonBanHang entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = this;
		}
		
		private void detach_hoaDonBanHangs(hoaDonBanHang entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = null;
		}
		
		private void attach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = this;
		}
		
		private void detach_phieunhaps(phieunhap entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieunhap")]
	public partial class phieunhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maphieunhap;
		
		private string _ngaynhap;
		
		private System.Nullable<int> _manv;
		
		private System.Nullable<int> _mancc;
		
		private System.Nullable<double> _tongtien;
		
		private EntitySet<chiTietPhieuNhap> _chiTietPhieuNhaps;
		
		private EntityRef<nhacungcap> _nhacungcap;
		
		private EntityRef<nhanVien> _nhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphieunhapChanging(int value);
    partial void OnmaphieunhapChanged();
    partial void OnngaynhapChanging(string value);
    partial void OnngaynhapChanged();
    partial void OnmanvChanging(System.Nullable<int> value);
    partial void OnmanvChanged();
    partial void OnmanccChanging(System.Nullable<int> value);
    partial void OnmanccChanged();
    partial void OntongtienChanging(System.Nullable<double> value);
    partial void OntongtienChanged();
    #endregion
		
		public phieunhap()
		{
			this._chiTietPhieuNhaps = new EntitySet<chiTietPhieuNhap>(new Action<chiTietPhieuNhap>(this.attach_chiTietPhieuNhaps), new Action<chiTietPhieuNhap>(this.detach_chiTietPhieuNhaps));
			this._nhacungcap = default(EntityRef<nhacungcap>);
			this._nhanVien = default(EntityRef<nhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieunhap", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maphieunhap
		{
			get
			{
				return this._maphieunhap;
			}
			set
			{
				if ((this._maphieunhap != value))
				{
					this.OnmaphieunhapChanging(value);
					this.SendPropertyChanging();
					this._maphieunhap = value;
					this.SendPropertyChanged("maphieunhap");
					this.OnmaphieunhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="Int")]
		public System.Nullable<int> manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._nhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mancc", DbType="Int")]
		public System.Nullable<int> mancc
		{
			get
			{
				return this._mancc;
			}
			set
			{
				if ((this._mancc != value))
				{
					if (this._nhacungcap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanccChanging(value);
					this.SendPropertyChanging();
					this._mancc = value;
					this.SendPropertyChanged("mancc");
					this.OnmanccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Float")]
		public System.Nullable<double> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieunhap_chiTietPhieuNhap", Storage="_chiTietPhieuNhaps", ThisKey="maphieunhap", OtherKey="maphieunhap")]
		public EntitySet<chiTietPhieuNhap> chiTietPhieuNhaps
		{
			get
			{
				return this._chiTietPhieuNhaps;
			}
			set
			{
				this._chiTietPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhacungcap_phieunhap", Storage="_nhacungcap", ThisKey="mancc", OtherKey="mancc", IsForeignKey=true)]
		public nhacungcap nhacungcap
		{
			get
			{
				return this._nhacungcap.Entity;
			}
			set
			{
				nhacungcap previousValue = this._nhacungcap.Entity;
				if (((previousValue != value) 
							|| (this._nhacungcap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhacungcap.Entity = null;
						previousValue.phieunhaps.Remove(this);
					}
					this._nhacungcap.Entity = value;
					if ((value != null))
					{
						value.phieunhaps.Add(this);
						this._mancc = value.mancc;
					}
					else
					{
						this._mancc = default(Nullable<int>);
					}
					this.SendPropertyChanged("nhacungcap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_phieunhap", Storage="_nhanVien", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public nhanVien nhanVien
		{
			get
			{
				return this._nhanVien.Entity;
			}
			set
			{
				nhanVien previousValue = this._nhanVien.Entity;
				if (((previousValue != value) 
							|| (this._nhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanVien.Entity = null;
						previousValue.phieunhaps.Remove(this);
					}
					this._nhanVien.Entity = value;
					if ((value != null))
					{
						value.phieunhaps.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(Nullable<int>);
					}
					this.SendPropertyChanged("nhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiTietPhieuNhaps(chiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.phieunhap = this;
		}
		
		private void detach_chiTietPhieuNhaps(chiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.phieunhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taiKhoan")]
	public partial class taiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _manv;
		
		private string _matkhau;
		
		private EntityRef<nhanVien> _nhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(int value);
    partial void OnmanvChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    #endregion
		
		public taiKhoan()
		{
			this._nhanVien = default(EntityRef<nhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._nhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(20)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_taiKhoan", Storage="_nhanVien", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public nhanVien nhanVien
		{
			get
			{
				return this._nhanVien.Entity;
			}
			set
			{
				nhanVien previousValue = this._nhanVien.Entity;
				if (((previousValue != value) 
							|| (this._nhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanVien.Entity = null;
						previousValue.taiKhoan = null;
					}
					this._nhanVien.Entity = value;
					if ((value != null))
					{
						value.taiKhoan = this;
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(int);
					}
					this.SendPropertyChanged("nhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
